const $=id=>document.getElementById(id);
const toast=(msg)=>{if(window.__switchieToast) window.__switchieToast(msg);};

/* ===== Layout editor logic ===== */
const EDITOR_KEY='switchie-layout-v1';
let editorOn=false,editorSelected=null,editorDrag=null,editorState={};
const EDITOR_EXCLUDE=new Set(['editToolbar','editHint','editTextPanel','editorOverlay','modalHost','toast','lobby']);
function editorId(el){if(!el||el===document.body||el===document.documentElement)return null;if(el.id)return '#'+el.id;const parts=[];let n=el;while(n&&n!==$('game')){let tag=n.tagName.toLowerCase(),i=1;let sib=n.previousElementSibling;while(sib){if(sib.tagName===n.tagName)i++;sib=sib.previousElementSibling}parts.unshift(`${tag}:nth-of-type(${i})`);n=n.parentElement}return '#game>'+parts.join('>')}
function editorLabel(el){if(!el)return 'Nothing selected';let t=(el.innerText||el.textContent||el.id||el.className||'Element').trim().replace(/\s+/g,' ');return t.slice(0,32)||el.id||'Element'}
function editorEligible(el){if(!el||!(el instanceof HTMLElement)||!$('game')?.contains(el))return false;if(EDITOR_EXCLUDE.has(el.id))return false;if(el.closest('#editToolbar,#editHint,#editTextPanel,#editorOverlay,#modalHost,#toast'))return false;if(el===document.querySelector('.table')||el===document.querySelector('.shell')||el===document.querySelector('.content')||el===document.querySelector('.center')||el===document.querySelector('.stage'))return false;return true}
function editorGet(el){const id=editorId(el);if(!id)return null;return editorState[id]||{id,text:null,x:0,y:0,s:1,r:0,label:editorLabel(el)} }
function editorApply(el){const st=editorGet(el);el.classList.add('editorTarget');el.style.setProperty('--edit-x',`${st.x||0}px`);el.style.setProperty('--edit-y',`${st.y||0}px`);el.style.setProperty('--edit-s',`${st.s||1}`);el.style.setProperty('--edit-r',`${st.r||0}deg`);if(st.text!=null && el.childElementCount===0)el.textContent=st.text}
function editorApplyAll(){document.querySelectorAll('#game *').forEach(el=>{if(editorEligible(el)){const id=editorId(el);if(editorState[id])editorApply(el)}});editorRefreshHandles()}
function editorSave(){try{localStorage.setItem(EDITOR_KEY,JSON.stringify(editorState))}catch(e){}}
function editorLoad(){try{const raw=localStorage.getItem(EDITOR_KEY);if(raw)editorState=JSON.parse(raw)||{}}catch(e){editorState={}}}
function editorRemoveSelection(){if(editorSelected){editorSelected.classList.remove('editorSelected','editorTextTarget');editorSelected=null}$('editorHandles').classList.remove('open');$('editTextPanel').classList.remove('open');$('editSelectionName').textContent='Nothing selected'}
function editorSelect(el){if(!editorEligible(el))return;editorRemoveSelection();editorSelected=el;editorApply(el);el.classList.add('editorSelected');if((el.childElementCount===0 || /^[^<>]+$/.test(el.textContent||'')) && (el.textContent||'').trim())el.classList.add('editorTextTarget');$('editSelectionName').textContent=editorLabel(el);editorRefreshHandles()}
function editorRefreshHandles(){const h=$('editorHandles');if(!editorSelected||!editorOn){h.classList.remove('open');return}const r=editorSelected.getBoundingClientRect();h.style.left=`${r.left}px`;h.style.top=`${r.top}px`;h.style.width=`${r.width}px`;h.style.height=`${r.height}px`;h.classList.add('open')}
function editorUpdate(){if(!editorSelected)return;const st=editorGet(editorSelected);editorState[st.id]=st;editorApply(editorSelected);editorRefreshHandles();editorSave()}
function editorStartMove(e){if(!editorOn||!editorSelected||e.target.closest('.editorHandle,.editorRotate'))return;if(e.button!==undefined&&e.button!==0)return;e.preventDefault();e.stopPropagation();const st=editorGet(editorSelected);editorDrag={type:'move',sx:e.clientX,sy:e.clientY,x:st.x||0,y:st.y||0};window.addEventListener('pointermove',editorPointerMove);window.addEventListener('pointerup',editorPointerUp,{once:true})}
function editorStartScale(e,handle){if(!editorSelected)return;e.preventDefault();e.stopPropagation();const r=editorSelected.getBoundingClientRect(),st=editorGet(editorSelected);editorDrag={type:'scale',sx:e.clientX,sy:e.clientY,w:r.width,h:r.height,s:st.s||1,handle,baseW:r.width,baseH:r.height};window.addEventListener('pointermove',editorPointerMove);window.addEventListener('pointerup',editorPointerUp,{once:true})}
function editorStartRotate(e){if(!editorSelected)return;e.preventDefault();e.stopPropagation();const r=editorSelected.getBoundingClientRect(),st=editorGet(editorSelected);editorDrag={type:'rotate',cx:r.left+r.width/2,cy:r.top+r.height/2,startAngle:Math.atan2(e.clientY-(r.top+r.height/2),e.clientX-(r.left+r.width/2))*180/Math.PI,r:st.r||0};window.addEventListener('pointermove',editorPointerMove);window.addEventListener('pointerup',editorPointerUp,{once:true})}
function editorPointerMove(e){if(!editorSelected||!editorDrag)return;const st=editorGet(editorSelected);if(editorDrag.type==='move'){st.x=editorDrag.x+(e.clientX-editorDrag.sx);st.y=editorDrag.y+(e.clientY-editorDrag.sy)}else if(editorDrag.type==='scale'){const dx=e.clientX-editorDrag.sx,dy=e.clientY-editorDrag.sy;let delta=(Math.abs(dx)>Math.abs(dy)?dx:dy);if(editorDrag.handle==='nw'||editorDrag.handle==='sw')delta=-delta;const factor=Math.max(.15,Math.min(5,editorDrag.s*(1+delta/Math.max(80,editorDrag.baseW))));st.s=factor}else if(editorDrag.type==='rotate'){const a=Math.atan2(e.clientY-editorDrag.cy,e.clientX-editorDrag.cx)*180/Math.PI;st.r=Math.round((editorDrag.r+a-editorDrag.startAngle)*10)/10}editorState[st.id]=st;editorApply(editorSelected);editorRefreshHandles()}
function editorPointerUp(){editorDrag=null;editorSave()}
function editorOpenText(){if(!editorSelected)return;const txt=editorSelected.childElementCount===0?editorSelected.textContent.trim():(editorSelected.innerText||'').trim();$('editTextArea').value=txt;$('editTextPanel').classList.add('open');$('editTextArea').focus()}
function editorApplyText(){if(!editorSelected)return;const v=$('editTextArea').value;const st=editorGet(editorSelected);st.text=v;editorState[st.id]=st;if(editorSelected.childElementCount===0)editorSelected.textContent=v;else editorSelected.innerText=v;editorSave();editorApply(editorSelected);editorRefreshHandles()}
function editorReset(){if(!editorSelected)return;const id=editorId(editorSelected);delete editorState[id];editorSelected.style.removeProperty('--edit-x');editorSelected.style.removeProperty('--edit-y');editorSelected.style.removeProperty('--edit-s');editorSelected.style.removeProperty('--edit-r');editorSelected.classList.remove('editorTarget');editorSelect(editorSelected)}
function editorResetAll(){editorState={};localStorage.removeItem(EDITOR_KEY);document.querySelectorAll('.editorTarget').forEach(el=>{el.style.removeProperty('--edit-x');el.style.removeProperty('--edit-y');el.style.removeProperty('--edit-s');el.style.removeProperty('--edit-r');el.classList.remove('editorTarget','editorSelected','editorTextTarget')});editorRemoveSelection()}
function editorExport(){const payload={version:1,stage:'Switchie',exportedAt:new Date().toISOString(),elements:editorState};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='switchie-layout.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function editorImport(file){if(!file)return;const rd=new FileReader();rd.onload=()=>{try{const p=JSON.parse(rd.result);editorState=p.elements||p||{};editorSave();editorApplyAll();toast('Layout imported')}catch(e){toast('Invalid layout JSON')}};rd.readAsText(file)}
function editorToggle(on=!editorOn){editorOn=on;document.documentElement.classList.toggle('editorOn',editorOn);$('editToolbar').classList.toggle('open',editorOn);$('editHint').classList.toggle('open',editorOn);if(editorOn){editorLoad();editorApplyAll()}else editorRemoveSelection()}
function editorInit(){editorLoad();$('editDone').onclick=()=>editorToggle(false);$('editExport').onclick=editorExport;$('editImport').onclick=()=>$('editFile').click();$('editFile').onchange=e=>editorImport(e.target.files[0]);$('editReset').onclick=editorReset;$('editResetAll').onclick=editorResetAll;$('editToggleText').onclick=editorOpenText;$('editTextApply').onclick=editorApplyText;$('editTextCancel').onclick=()=>$('editTextPanel').classList.remove('open');$('game').addEventListener('pointerdown',e=>{if(!editorOn)return;if(e.target.closest('#editToolbar,#editTextPanel,#editorHandles'))return;let el=e.target;while(el&&el!==$('game')&&!editorEligible(el))el=el.parentElement;if(editorEligible(el)){editorSelect(el);editorStartMove(e)}else editorRemoveSelection()});$('game').addEventListener('dblclick',e=>{if(!editorOn)return;if(editorSelected&&editorSelected.contains(e.target))editorOpenText()});$('editorHandles').addEventListener('pointerdown',e=>{const h=e.target.closest('.editorHandle,.editorRotate');if(!h||!editorSelected)return;const type=h.dataset.handle;if(type==='rotate')editorStartRotate(e);else editorStartScale(e,type)});window.addEventListener('resize',()=>editorRefreshHandles());const b=document.createElement('button');b.id='editorLaunch';b.type='button';b.textContent='✎ Edit Layout';b.title='Open the visual layout editor (Alt+E)';b.style.cssText='position:fixed;left:50%;top:12px;transform:translateX(-50%);z-index:9000;display:none;background:linear-gradient(145deg,#1b211c,#090e0b);border:1px solid #d6b15d99;color:#f2dfaa;border-radius:8px;padding:8px 12px;font-size:11px;box-shadow:0 8px 18px #0009';document.body.appendChild(b);b.onclick=()=>editorToggle(true);window.addEventListener('keydown',e=>{if(e.key==='Escape'&&editorOn)editorToggle(false);if(e.key==='e'&&e.altKey&&$('game').style.display!=='none')editorToggle(!editorOn)});const obs=new MutationObserver(()=>{if(editorOn)requestAnimationFrame(editorApplyAll)});obs.observe($('game'),{childList:true,subtree:true});window.showEditorButton=()=>{b.style.display='block'};window.hideEditorButton=()=>{b.style.display='none'};editorInitDone=true}
let editorInitDone=false;
if(document.readyState==='loading') window.addEventListener('DOMContentLoaded',()=>{ if(!editorInitDone) editorInit(); },{once:true}); else if(!editorInitDone) editorInit();


